spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voting_db
    username: postgres
    password: postgres
    initialization-mode: never
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        use_sql_comments: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
logging:
  level:
    org:
      hibernate:
        type: trace

jwt:
  signing:
    key:
      secret: mySecret
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800